### ISSUE TITLE
[feature] Prevent abusing for do$h printing

### ISSUE THREAD

**Issue by Vel-San** [InsultingPros/SpawnWeapons#1]
@Shtoyan 

I've used a similar Mut before, but always hate it because they can be abused to print free Dolla bills a.k.a DO$H. I haven't checked the code but:

- These kinds of mutators should always consider **_when_** did the player spawn. Is it at the start of the game? Is it mid-game? Is it after the wave ended and they are heading to buy some ice cream from the trader?

Abuse use-case: Trader wave started, player drops his current weapons, player suicides, the player now has 2x of each spawned weapon, player sells the dupes and boom, you're now getting a free shit ton of do$h every wave end!

That's one of the main reasons I decided to create the WeaponStatsConfig mutator, and nerf some of the hard-hitting weapons to avoid "removing" them from the game and replace spawn weapons with such mutators.

This will also put more overload on the server if the server doesn't clear weapons from the ground after every wave. (WeaponsStay)

**Comment by Shtoyan** [comment]
There are so many easy ways to get dosh, should we even try to prevent it? :p

And in the end dosh doesn't save you if your hands can't hold them and kill the zeds at same time.

**Comment by dkanus** [comment]
While I don't that think dosh generation through suicide is a huge problem, it is definitely something that should be fixed.

I'd say a good option would be to set the cost of every spawn weapon, except the first one player gets, to zero.

**Comment by Vel-San** [comment]
> There are so many easy ways to get dosh, should we even try to prevent it? :p
> 
> And in the end dosh doesn't save you if your hands can't hold them and kill the zeds at same time.

I mean it's called a patch for a reason 🐛 AFAIK Acedia already fixes weapon printing, so if this can be fixed within this mutator, maybe it can also be ported to acedia and you don't have to implement such things in this mutator.. make it kind of a universal thingie.

> While I don't that think dosh generation through suicide is a huge problem, it is definitely something that should be fixed.
> 
> I'd say a good option would be to set the cost of every spawn weapon, except the first one player gets, to zero.

There's a ton of ways that you patch this, just like you said, in addition to:

- Make suicide on trader actually "Suicide", and you won't spawn after it. Anyway if you suicide twice on the trader, you will not spawn.
- Keep a track of players who suicide, and give them no dosh on respawn or new weapons
- Make weapons not drop if someone commits Roblox oof

And the list goes on.

**Comment by dkanus** [comment]
I feel like these changes are somewhat out of scope for this simple mutator. But tracking players, for whom `ReplaceWeapons()` was already called, should be easy by using SteamID. Will try to find time to test it later this or next week.

I'll add a more comprehensive fix for Acedia 0.2 plans. That version's scope got expanded from just bug fixes and it got somewhat... sizable. Still needs quite a bit more work - the best case scenario is being out somewhere near the end of the year, but probably later.

**Comment by dkanus** [comment]
This is now fixed in 73d45b42484aa84433dd597c4fc1ae394222f804
